import React, { useEffect, useState, useContext } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import axios from 'axios'
import styles from '../styles/Home.module.css'

import { Coin, CoinList } from '../config/coingecko'
import { ThemeContext } from '../contexts'

const Home: NextPage<{ coins: Coin[] }> = (props: { coins: Coin[] }) => {
  const [currency, setCurrency] = useState('USD')
  // const [coins, setCoins] = useState([])
  const [loading, setLoading] = useState(false)
  const { theme } = useContext(ThemeContext)

  // const fetchCoins = async () => {
  //   setLoading(true)
  //   const { data } = await axios.get(CoinList('USD'))
  //   setCoins(data)
  //   setLoading(false)
  // }

  // useEffect(() => {
  //   fetchCoins()
  // }, [currency])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {props.coins &&
          props.coins.map((coin: Coin) => <div>{coin.symbol}</div>)}
      </main>
    </div>
  )
}

Home.getInitialProps = async () => {
  const { data } = await axios.get(CoinList('USD'))
  return { coins: data }
}

export default Home
